// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagVv8vkwfXyh-9FIEZbPoybD69jh_El8',
    appId: '1:304311437492:web:46aa166cd4cfc92021afe1',
    messagingSenderId: '304311437492',
    projectId: 'shadowpass',
    authDomain: 'shadowpass.firebaseapp.com',
    storageBucket: 'shadowpass.appspot.com',
    measurementId: 'G-VFYKPF8EM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YqA4iRPdZWdZCp6TQg9tIXgb6JQvQGc',
    appId: '1:304311437492:android:46cb7fd948a1a41721afe1',
    messagingSenderId: '304311437492',
    projectId: 'shadowpass',
    storageBucket: 'shadowpass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKX7TCcMD-lAWbblZdgOvh-MqBXzmfkQo',
    appId: '1:304311437492:ios:371c3dc190e1c4eb21afe1',
    messagingSenderId: '304311437492',
    projectId: 'shadowpass',
    storageBucket: 'shadowpass.appspot.com',
    iosClientId: '304311437492-7rtfj5k57mi0kf1etu3cfm9426vv8476.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKX7TCcMD-lAWbblZdgOvh-MqBXzmfkQo',
    appId: '1:304311437492:ios:9fcaa351f6b41fb821afe1',
    messagingSenderId: '304311437492',
    projectId: 'shadowpass',
    storageBucket: 'shadowpass.appspot.com',
    iosClientId: '304311437492-b1p0m2tfiss15to0tgr6tde6qk2m07ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.shadowpass.RunnerTests',
  );
}
